# Generated by Django 5.2.7 on 2025-11-12 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0004_alter_tag_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="blog",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="blog_app.blog",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="posts",
            field=models.ManyToManyField(related_name="tags", to="blog_app.post"),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("blog", "name"), name="unique_tag_per_blog"
            ),
        ),
    ]
