# Generated by Django 5.2.7 on 2025-11-12 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0005_tag_blog_alter_tag_posts_tag_unique_tag_per_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="blog_app.blog",
            ),
        ),
    ]
